"""Netra Common Models Package."""

from netra_common.models.email import (
    IngestionEvent,
    AttachmentMetadata,
    EmailHeaders,
    ParsedEmail,
    HeaderAnalysisResult,
    DetectedTyposquat,
    UrlAnalysisResult,
    ContentAnalysisResult,
    FlaggedAttachment,
    AttachmentAnalysisResult,
    AnalysisResults,
    AnalyzedEmail,
    ThreatVerdict,
    IOCItem,
    RuleContribution,
    ThreatIntelligence,
    ClassifiedEmail,
    EnrichedIOC,
    EnrichmentData,
    EnrichedEmail,
    CorrelationData,
    CorrelatedEmail,
)

__all__ = [
    "IngestionEvent",
    "AttachmentMetadata",
    "EmailHeaders",
    "ParsedEmail",
    "HeaderAnalysisResult",
    "DetectedTyposquat",
    "UrlAnalysisResult",
    "ContentAnalysisResult",
    "FlaggedAttachment",
    "AttachmentAnalysisResult",
    "AnalysisResults",
    "AnalyzedEmail",
    "ThreatVerdict",
    "IOCItem",
    "RuleContribution",
    "ThreatIntelligence",
    "ClassifiedEmail",
    "EnrichedIOC",
    "EnrichmentData",
    "EnrichedEmail",
    "CorrelationData",
    "CorrelatedEmail",
]
